sources:
  - generated/CormorantInfant.glyphs
  - generated/CormorantInfant-Italic.glyphs
axisOrder:
  - wght
  - ital
familyName: Cormorant Infant
buildStatic: False
buildWebfont: True
buildSmallCap: False
postCompile:
  - operation: rename
    args: --just-family
    name: Cormorant Infant
stat:
  CormorantInfant[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  CormorantInfant-Italic[wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
      
